### ISSUE TITLE
Question: Can `ramp-eu/FIREFIT-deprecated` be safely deleted?

### ISSUE THREAD

**Issue by jason-fox** [Introsys/FIREFIT.ROSE-AP#6]
* `Introsys/FIREFIT.ROSE-API` is  the master repo/ source of truth
* `ramp-eu/FIREFIT` is a fork and regularly updated clone
* `ramp-eu/FIREFIT-deprecated` is the original RAMP Repo

Are there any useful files that still need to be ported across from `ramp-eu/FIREFIT-deprecated` or can it be deleted?

**Comment by magnoguedes** [comment]
Hi Jason,

`ramp-eu/FIREFIT-deprecated` can be deleted.

Thanks.

**Comment by jason-fox** [comment]
Deleted
